name: Nightly Flutter APK

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 1 * * *" # runs daily at 01:00 UTC
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.41.6"
  BASE_URL: ${{secrets.BASE_URL}}
  APK_NAME: app-nightly-${{ github.run_number }}.apk

jobs:
  build-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Set nightly APK name
        run: |
          DATE=$(date +'%Y%m%d')
          echo "APK_NAME=app-nightly-${DATE}-${GITHUB_RUN_NUMBER}.apk" >> $GITHUB_ENV

      - name: Build release APK
        run: flutter build apk --release --no-shrink --dart-define=BASE_URL=$BASE_URL

      - name: Prepare release file
        run: |
          mkdir -p release
          mv build/app/outputs/flutter-apk/app-release.apk release/$APK_NAME

      - name: Upload nightly APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: release/${{ env.APK_NAME }}
          if-no-files-found: error
